[package]
name = "ib2c"
version = "0.1.0"
edition = "2024"

[dependencies]
module = { path = "../module" }
ports = { path = "../ports" }
meta_signals = { path = "../meta_signals" }
derive_more = { version = "2.0.1", features = ["deref", "deref_mut"] }
